before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libxml2 libssh2-1-dev clang cmake -y
  - sudo apt-get build-dep curl -y

language: c++

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
