sudo: false

git:
    submodules: false
    
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - build-essential
    - libxml2
    - libssh2-1-dev
    - clang
    - cmake

compiler:
    - clang

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  
language: c++

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make
