
sudo: false

git:
    submodules: false

before_install:
  - apt-get update -qq
  - apt-get install build-essential libxml2 libssh2-1-dev clang cmake -y
  - apt-get build-dep curl -y
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  
language: c++

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
