sudo: false

git:
    submodules: false
    
addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - build-essential
    - libxml2
    - libssh2-1-dev
    - clang-3.6

compiler:
  - clang-3.6

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar -xvf /tmp/cmake.tar.gz 
  - export PATH=$PATH:$PWD/cmake-3.3.1-Linux-x86_64/bin/ 

language: c++

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
